networks:
  tlmaster-network:
    driver: bridge

volumes:
  postgres-volume:

services:

  # db:
  #   image: mcr.microsoft.com/mssql/server:latest
  #   ports:
  #     - 1433:1433
  #   restart: unless-stopped
  #   environment:
  #     ACCEPT_EULA: Y 
  #     MSSQL_SA_PASSWORD: DevelopmentPW1! 
  #     MSSQL_PID: Developer
  #   volumes:
  #     - sqlserver-volume:/var/opt/mssql
  #   networks:
  #     - tlmaster-network

  db:
    image: postgres:16
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: tlmaster 
      POSTGRES_USER: tlmaster 
      POSTGRES_DB: tlmaster
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - tlmaster-network
  
#   api:
#     ports:
#       - 5001:80
#       - 7001:443
#     restart: unless-stopped
#     build:
#       context: .
#       dockerfile: TLMaster/Dockerfile
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://+:80;
# #     - ConnectionStrings__ConnectionString=Server=db,1433;Database=TLMasterDB;User Id=sa;Password=DevelopmentPW1!;TrustServerCertificate=true;
#       - ConnectionStrings__ConnectionString=Server=db,5432;Database=tlmaster;User id=tlmaster;Password=tlmaster;
#     networks:
#       - tlmaster-network
#     depends_on: 
#       - db

